import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { NavBar } from "./components/NavBar";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="max-w-screen">
        <NavBar></NavBar>
      </header>
      <main className="flex min-h-screen min-w-min flex-col items-center justify-center ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 "></div>
      </main>
    </>
  );
}
